
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (1,'BTCL ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (2,'GETCO ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (3,'M&H ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (4,'Paradise ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (5,'Teleplus NY ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (6,'Bantel ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (7,'Beximco ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (8,'Cloud Tel ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (9,'Bangla ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (10,'VOICETEL ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (11,'Imam Network ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (12,'ISL Sheba ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (13,'Mother Telecom ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (14,'Agni Systems ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (15,'New Generation Telecom ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (16,'Softex Communication ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (17,'Sengupta Telecom ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (18,'RingTech ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (19,'Purple ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (20,'Gazi ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (21,'Micro Trade ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (22,'Tele Exchange ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (23,'MM Communications ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (24,'SR Telecom ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (25,'Bangla Telecom ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (26,'Vertex ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (27,'Jibondhara ICX',1,2);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (28,'Bangla Trac Communication IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (29,'Mir Telecom IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (30,'Novotel IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (31,'Global Voice Telecom Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (32,'BG Tel Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (33,'HRC Technologies Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (34,'Roots Communication IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (35,'IAsia Alliance Gateway IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (36,'Unique Infowary LImited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (37,'Sigma Engineers Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (38,'Telex Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (39,'DBL Telecom Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (40,'Apple Network Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (41,'First Communications Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (42,'Kay Telecommunications Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (43,'Ratul Telecom Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (44,'Mos5 Tel Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (45,'Cel Telecom Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (46,'Ranks Telecom Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (47,'Bangla Tel Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (48,'SM Communication Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (49,'Platinum Communications Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (50,'Vision Tel Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (51,'Banaladesh International Gatway limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (52,'Digicon Telecommunication Limited IGW',1,4);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (53,'GRAMEENPHONE',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (54,'ROBI (AKTEL)',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (55,'BANGLALINK',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (56,'AIRTEL',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (57,'CITYCELL',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (58,'TELETALK',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (59,'BTCL',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (60,'WORLDTEL',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (61,'BAYPHONES(WESTERN)',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (62,'BANGLAPHONE',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (63,'SUNTEL(TELEBARTA/JUBOK)',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (64,'NATIONALPHONE',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (65,'PEOPLESTEL',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (66,'SATELECOM',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (67,'SHEBAPHONE',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (68,'RANKSTEL',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (69,'JALALABADTELECOM',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (70,'ONETEL',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (71,'DHAKAPHONE',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (72,'BTSCOMMUNICATIONS',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (73,'ISNLTD.',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (74,'ROYALGREENONLINE',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (75,'FUSION NET',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (76,'AGNISYSTEMSLTD.',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (77,'DIGITALCONNECTIVITYLTD.',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (78,'BEXIMCOLTD.',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (79,'DHAKACOM',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (80,'METRONET',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (81,'HRC-TECH (GETCO)',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (82,'DNS (BD Internet Exchange)',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (83,'NEXTONLINE LTD.',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (84,'GRAMEENCYBERNET LTD.',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (85,'Talktell (JF Optics)',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (86,'BDCOMONLINE LTD.',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (87,'CONNECTBD',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (88,'LINK3 TECHNOLOGIES',1,1);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (89,'Telewave',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (90,'British Telecom',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (91,'Maya Technologies LTD',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (92,'Nescafe',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (93,'E-Express',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (94,'FMK NET',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (95,'M A Enterprise',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (96,'TB Tel',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (97,'Marshal Telecom',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (98,'RAL Express',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (99,'Western Service',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (101,'Osel Tel',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (102,'Live Talk NetZone',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (103,'Mehak Trading LLC',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (104,'Telewave_B',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (105,'KHALEEJ TRADING CO',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (106,'Mahmud International',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (107,'ICC Telecom',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (108,'world computer',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (109,'Dahicom USA',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (110,'Roots Communications Inc.',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (111,'MAHMUD INTERNATIONAL UK',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (112,'CALLCARRIER INTERNATIONAL',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (113,'Shahnaz Enterprise',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (114,'Simple Telecom',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (115,'MAH TELECOM',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (116,'VENNERVOICE COMMUNICATIONS',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (117,'Phonetime Inc',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (118,'ARTS TELECOM, UK',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (119,'Trusted Network Technology (T.N.T)',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (120,'First Solution USA Inc',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (121,'Alpha One Hong kong, Hk',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (122,'FIZAN TEL LIMITED',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (123,'East West Telecom LLC',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (124,'CKR International Inc,USA',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (125,'International Access',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (126,'Manor IT',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (127,'Core IT Solution Ltd.',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (128,'M1 Communications',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (129,'SIDO TEL',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (130,'Fahad bin Sayed bin Salem Al-Falahi Trading',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (131,'Tata Communications International Pte Ltd',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (132,'Shinetown Telecommunication Limited',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (133,'Ivoco Limited',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (134,'DiGi',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (135,'Digital World Communications',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (136,'Quickcom Global Communications Limited',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (137,'Voice Trader Ltd',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (138,'Citycom Global',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (139,'Nexwave',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (140,'TELECOM SERVICES NETWORK LLC',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (141,'MnM Telecom',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (142,'ADG LDI',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (143,'Virtual American Companies LLC',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (144,'Bharti Airtel',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (145,'Dialog Axiata PLC',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (146,'ICOM Voice',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (147,'New World Telecommunications Ltd.(NWT)',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (148,'Mega Target',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (149,'Telebiz Interconnectional FZC',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (150,'Netelsat FZE',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (151,'Voice World (HK)',1,3);
insert into carrier (idcarrier,carriername,customerprepaid,carriertype) values (152,'Nightingale Communication & Services Pte. Ltd',1,3);
