insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (1  ,'BTCL ICX'                                     ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (2  ,'GETCO ICX'                                    ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (3  ,'M&H ICX'                                      ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (4  ,'Paradise ICX'                                 ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (5  ,'Teleplus NY ICX'                              ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (6  ,'Bantel ICX'                                   ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (7  ,'Beximco ICX'                                  ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (8  ,'Cloud Tel ICX'                                ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (9  ,'Bangla ICX'                                   ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (10 ,'VOICETEL ICX'                                 ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (11 ,'Imam Network ICX'                             ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (12 ,'ISL Sheba ICX'                                ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (13 ,'Mother Telecom ICX'                           ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (14 ,'Agni Systems ICX'                             ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (15 ,'New Generation Telecom ICX'                   ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (16 ,'Softex Communication ICX'                     ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (17 ,'Sengupta Telecom ICX'                         ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (18 ,'RingTech ICX'                                 ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (19 ,'Purple ICX'                                   ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (20 ,'Gazi ICX'                                     ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (21 ,'Micro Trade ICX'                              ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (22 ,'Tele Exchange ICX'                            ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (23 ,'MM Communications ICX'                        ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (24 ,'SR Telecom ICX'                               ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (25 ,'Bangla Telecom ICX'                           ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (26 ,'Vertex ICX'                                   ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (27 ,'Jibondhara ICX'                               ,'sales@dummy.com',1,2,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (28 ,'Bangla Trac Communication IGW'                ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (29 ,'Mir Telecom IGW'                              ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (30 ,'Novotel IGW'                                  ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (31 ,'Global Voice Telecom Limited IGW'             ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (32 ,'BG Tel Limited IGW'                           ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (33 ,'HRC Technologies Limited IGW'                 ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (34 ,'Roots Communication IGW'                      ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (35 ,'IAsia Alliance Gateway IGW'                   ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (36 ,'Unique Infowary LImited IGW'                  ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (37 ,'Sigma Engineers Limited IGW'                  ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (38 ,'Telex Limited IGW'                            ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (39 ,'DBL Telecom Limited IGW'                      ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (40 ,'Apple Network Limited IGW'                    ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (41 ,'First Communications Limited IGW'             ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (42 ,'Kay Telecommunications Limited IGW'           ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (43 ,'Ratul Telecom Limited IGW'                    ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (44 ,'Mos5 Tel Limited IGW'                         ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (45 ,'Cel Telecom Limited IGW'                      ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (46 ,'Ranks Telecom Limited IGW'                    ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (47 ,'Bangla Tel Limited IGW'                       ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (48 ,'SM Communication Limited IGW'                 ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (49 ,'Platinum Communications Limited IGW'          ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (50 ,'Vision Tel Limited IGW'                       ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (51 ,'Banaladesh International Gatway limited IGW'  ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (52 ,'Digicon Telecommunication Limited IGW'        ,'sales@dummy.com',1,4,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (53 ,'GRAMEENPHONE'                                 ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (54 ,'ROBI (AKTEL)'                                 ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (55 ,'BANGLALINK'                                   ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (56 ,'AIRTEL'                                       ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (57 ,'CITYCELL'                                     ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (58 ,'TELETALK'                                     ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (59 ,'BTCL'                                         ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (60 ,'WORLDTEL'                                     ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (61 ,'BAYPHONES(WESTERN)'                           ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (62 ,'BANGLAPHONE'                                  ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (63 ,'SUNTEL(TELEBARTA/JUBOK)'                      ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (64 ,'NATIONALPHONE'                                ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (65 ,'PEOPLESTEL'                                   ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (66 ,'SATELECOM'                                    ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (67 ,'SHEBAPHONE'                                   ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (68 ,'RANKSTEL'                                     ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (69 ,'JALALABADTELECOM'                             ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (70 ,'ONETEL'                                       ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (71 ,'DHAKAPHONE'                                   ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (72 ,'BTSCOMMUNICATIONS'                            ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (73 ,'ISNLTD.'                                      ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (74 ,'ROYALGREENONLINE'                             ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (75 ,'FUSION NET'                                   ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (76 ,'AGNISYSTEMSLTD.'                              ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (77 ,'DIGITALCONNECTIVITYLTD.'                      ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (78 ,'BEXIMCOLTD.'                                  ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (79 ,'DHAKACOM'                                     ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (80 ,'METRONET'                                     ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (81 ,'HRC-TECH (GETCO)'                             ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (82 ,'DNS (BD Internet Exchange)'                   ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (83 ,'NEXTONLINE LTD.'                              ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (84 ,'GRAMEENCYBERNET LTD.'                         ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (85 ,'Talktell (JF Optics)'                         ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (86 ,'BDCOMONLINE LTD.'                             ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (87 ,'CONNECTBD'                                    ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (88 ,'LINK3 TECHNOLOGIES'                           ,'sales@dummy.com',1,1,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (89 ,'Telewave'                                     ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (90 ,'British Telecom'                              ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (91 ,'Maya Technologies LTD'                        ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (92 ,'Nescafe'                                      ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (93 ,'E-Express'                                    ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (94 ,'FMK NET'                                      ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (95 ,'M A Enterprise'                               ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (96 ,'TB Tel'                                       ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (97 ,'Marshal Telecom'                              ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (98 ,'RAL Express'                                  ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (99 ,'Western Service'                              ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (101,'Osel Tel'                                     ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (102,'Live Talk NetZone'                            ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (103,'Mehak Trading LLC'                            ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (104,'Telewave_B'                                   ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (105,'KHALEEJ TRADING CO'                           ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (106,'Mahmud International'                         ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (107,'ICC Telecom'                                  ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (108,'world computer'                               ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (109,'Dahicom USA'                                  ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (110,'Roots Communications Inc.'                    ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (111,'MAHMUD INTERNATIONAL UK'                      ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (112,'CALLCARRIER INTERNATIONAL'                    ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (113,'Shahnaz Enterprise'                           ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (114,'Simple Telecom'                               ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (115,'MAH TELECOM'                                  ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (116,'VENNERVOICE COMMUNICATIONS'                   ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (117,'Phonetime Inc'                                ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (118,'ARTS TELECOM, UK'                             ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (119,'Trusted Network Technology (T.N.T)'           ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (120,'First Solution USA Inc'                       ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (121,'Alpha One Hong kong, Hk'                      ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (122,'FIZAN TEL LIMITED'                            ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (123,'East West Telecom LLC'                        ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (124,'CKR International Inc,USA'                    ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (125,'International Access'                         ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (126,'Manor IT'                                     ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (127,'Core IT Solution Ltd.'                        ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (128,'M1 Communications'                            ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (129,'SIDO TEL'                                     ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (130,'Fahad bin Sayed bin Salem Al-Falahi Trading'  ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (131,'Tata Communications International Pte Ltd'    ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (132,'Shinetown Telecommunication Limited'          ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (133,'Ivoco Limited'                                ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (134,'DiGi'                                         ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (135,'Digital World Communications'                 ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (136,'Quickcom Global Communications Limited'       ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (137,'Voice Trader Ltd'                             ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (138,'Citycom Global'                               ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (139,'Nexwave'                                      ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (140,'TELECOM SERVICES NETWORK LLC'                 ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (141,'MnM Telecom'                                  ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (142,'ADG LDI'                                      ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (143,'Virtual American Companies LLC'               ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (144,'Bharti Airtel'                                ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (145,'Dialog Axiata PLC'                            ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (146,'ICOM Voice'                                   ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (147,'New World Telecommunications Ltd.(NWT)'       ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (148,'Mega Target'                                  ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (149,'Telebiz Interconnectional FZC'                ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (150,'Netelsat FZE'                                 ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (151,'Voice World (HK)'                             ,'sales@dummy.com',1,3,1,0);
insert into carrier (idcarrier,carriername,email,customerprepaid,carriertype,billingdate,timezone) values (152,'Nightingale Communication & Services Pte. Ltd','sales@dummy.com',1,3,1,0);
